review_version: 2.0
bookname: grnbook-ja
booktitle: Groongaではじめる全文検索
aut: 北市真
edt: 須藤功平
language: ja
date: 2017-02-09 初
epubversion: 3
coverimage: cover.png
highlight:
  html: pygments
  latex: listings
stylesheet: main.css
texstyle: samplemacro
urnid: https://github.com/KitaitiMakoto/grnbook-ja
